Add WalletList and WalletDetail Views
chedug/Wallet pull request #1
Opened 2023-08-04 10:55 UTC by chedug

Now it's possible to view all wallets using "wallets/" endpoint, and view details of each wallet using "wallets/<str:name>" endpoints.

2023-08-07 15:09 UTC, VladKli commented on requirements.txt
I do not see django, DRF packages. Could you double check if all necessary dependencies are in the file?

2023-08-07 15:11 UTC, chedug commented on requirements.txt
Oh, sorry, didn't notice that the comment is about requirements.txt. I will add it later, thank you for pointing that out.

2023-08-08 07:31 UTC, VladKli commented on testproject/wallets/models.py
- split wallets and transactions into different applications.
Wallet:
1. function `create_random_name()` move to the class
2. id is unnecessary field 
3. for fields type and currency set default values
4. created_on,  modified_on null-False

Transactions:
1. for sender, receiver change related_name, and set attr to_field=name
2. set transfer_amount to 0.00 
3. commission, timestamp editable=False
4. status set to default

2023-08-08 07:33 UTC, VladKli commented on testproject/wallets/serializers.py
> +    user = serializers.ReadOnlyField(source="user.username")
check what's PrimaryKeyRelatedField and compare which one is better to use

2023-08-08 07:38 UTC, VladKli commented on testproject/wallets/serializers.py
> +            balance = 0.00
check this condition, please

2023-08-09 10:12 UTC, chedug commented on testproject/transactions/serializers.py
> +    def validate_transfer_amount(self, validated_data):
Error: When making POST request, validated_data consists of only Decimal("0") value (default value for transfer_amount).

2023-08-10 08:21 UTC, chedug commented on testproject/transactions/serializers.py
> +    def validate_transfer_amount(self, validated_data):
Fixed error by renaming function to validate_sender_money (How?)

2023-08-10 08:22 UTC, chedug commented on testproject/wallets/serializers.py
> +    wallets = serializers.RelatedField(many=True, read_only=True)
Done

2023-08-10 08:22 UTC, chedug commented on testproject/wallets/serializers.py
> +        if Wallet.objects.filter(user=user).count() >= 5:
Done

2023-08-11 11:50 UTC, VladKli requested changes
1. urls
2. create constant variables for number of wallet, bonuses, etc. use UPPER_CASE
3. remove UserSerializer as we don't use it. correct urls and views accordingly
4. views. attrs should be at the beginning of a class then methods
5. WalletDetail(generics.RetrieveUpdateDestroyAPIView). we need only retrieve, delete
6. permissions
7. logic.py -> utils.py

2023-08-16 15:44 UTC, VladKli requested changes
1. add endpoints related to authorization to the registration app, login, logout. correct UserRegistrationView (it shouldn't return 500 error when user doesn't provide username or any other field during registration)
2. pre-commit
3. add types annotations
4. remove unused code

2023-08-18 13:02 UTC, VladKli approved these changes

2023-08-18 13:06 UTC, merged